#!/usr/bin/env bash
git push origin main &&
(git branch -D gh-pages || echo "no gh-pages branch to delete: passing") &&
git checkout -b gh-pages &&
npm run build &&
git add index.html style.css -f &&
git commit -m 'update build' &&
git push origin --force gh-pages &&
git checkout main
