graph BT

  work -->|author| human
  work -->|serie| serie
  work -->|subject| subject
  work -->|genre| genre
  serie -->|author| human
  serie -->|subject| subject
  serie -->|genre| genre
  edition -->|translator| human
  edition -->|author of foreword/afterword| human
  edition -->|edition of| work
  edition -->|publisher| publisher
  edition -->|collection| collection
  collection -->|publisher| publisher
  item --> edition

  classDef wikidata fill:#22ff2288,stroke-width:0;
  classDef both fill:#31ffc2,stroke-width:0;
  classDef inventaire fill:#319cc288,stroke-width:0;
  classDef notanentity fill:#eee,stroke-width:0;

  class subject,genre wikidata;
  class work,human,serie,publisher,collection both;
  class edition inventaire;
  class item notanentity;
